# Generated by Django 3.1.7 on 2021-03-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_auto_20210319_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=400)),
                ('itemsCompleted', models.IntegerField(default=0)),
                ('colorTheme', models.CharField(choices=[('o', 'orange'), ('p', 'purple'), ('b', 'blue'), ('g', 'green')], default='o', max_length=15)),
            ],
        ),
    ]
