# Generated by Django 3.1.7 on 2021-04-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_userprofileinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='dateAdded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='profileHidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
    ]
