# Generated by Django 3.1.7 on 2021-04-17 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchlist', '0005_auto_20210413_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('postType', models.CharField(choices=[('f', 'finished'), ('s', 'started')], max_length=1)),
                ('itemName', models.CharField(max_length=200)),
                ('hidden', models.BooleanField(default=False)),
                ('listItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.listitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
