# Generated by Django 3.1.7 on 2021-04-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0006_profileactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='profileHidden',
            new_name='isProfileHidden',
        ),
    ]
